name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - name: Check Out GitHub
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: ${{ secrets.MAVEN_USERNAME }}
        server-password: ${{ secrets.MAVEN_PASSWORD }}
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Test with Maven
      run: mvn clean test -f pom.xml -s $GITHUB_WORKSPACE/settings.xml
