name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      
    steps:
    - name: Check Out GitHub
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Test with Maven
      env: 
        USERNAME: ${{ secrets.MAVEN_USERNAME }}
        PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      run: mvn clean test -s settings.xml 
        
